version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tahca
      POSTGRES_PASSWORD: banco123
      POSTGRES_DB: parking-control-db
    ports:
      - 5433:5432
    expose:
      - 5433

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080